Layered can
modelica/fmi-standard pull request #1091
Opened 2020-07-28 12:25 UTC by andreas-junghanns

First start, most technical issues are in, format still unclear, example missing.
This is getting more pressing as an example for the eFMI people to write their standard layered on top of FMI 3.0.

Format: Pierre can you help?

Content: Pierre, anything important I am missing?

Example: ChristianS - I am waiting for a Terminal&Icon example to adapt manually to a simple CAN bus example. Please let me know when you have something available ASAP.

Build: TorstenS: I have added a standalone .adoc - improvement suggestions?

2020-07-29 13:41 UTC, chrbertsch commented
@andreas-junghanns : why not use "." as a separator instead of "::" as with structured variable names in FMUs? Could be helpful to keep tools consistent for "normal variables" and "CAN variables.

2020-07-29 15:10 UTC, andreas-junghanns commented
> @andreas-junghanns : why not use "." as a separator instead of "::" as with structured variable names in FMUs? Could be helpful to keep tools consistent for "normal variables" and "CAN variables.

Specifically for the reasons of indicating that CAN signals are NOT normal variables, a different separator might be a good idea.
Note: The DBC specification I have does not allow '.' inside a signal or message name, so in theory it would work as separator (not sure about ARXML, I did not check there).

The '.' separator indicates Modelica or C hierarchies.
Using "::" indicates better a different hierarchy: that of a communication bus.
We could define a new `variableNamingConvention = busHierarchy` that uses "::" as separator.
But unfortunately, we can only have one variable naming convention right now (attribute variableNamingConvention in <fmiModelDescription>) and we cannot mix then 'structured' and 'busHierarchy'.
We might have to use 'structuredAndBus' to indicate both are used and that both separators are in use.

Summary:
I think the strongest argument pro "::" is the simple differentiation between C/Modelica variables and bus signals that have completely different semantics (e.g. clocked variables).

2020-07-30 12:31 UTC, chrbertsch commented
We should perhaps point out explicitely that this describes an idealized bus, exposing signals as FMI Terminals/Variables and not considering real bus behaviour like

- Bus arbitration: CAN messages are sent according to priority (determined by Frame_ID).
- Potocol functions: i.e. CAN Request for retransmit is a specific protocol function.
- Buffer overflow: when an ECU receives more messages than its buffer can hold.
- Bus errors: electrical errors which cause failed message transmission.
- Bus congestion: too many CAN messages for the bandwidth of the bus.

2020-07-30 19:20 UTC, andreas-junghanns commented
> We should perhaps point out explicitely that this describes an idealized bus, exposing signals as FMI Terminals/Variables and not considering real bus behaviour like

Thanks, excellent and comprehensive list, added as proposed.

2020-09-02 12:23 UTC, andreas-junghanns commented
I have not received feedback for a while and that must mean all is well. I will merge this PR at the end of this week, unless you stop me.

2020-09-02 12:58 UTC, chrbertsch commented
@andreas-junghanns : please to not yet merge this. We just had a company-internal discussion on this and will provide additional feedback. Thanks!

2020-09-02 15:01 UTC, chrbertsch requested changes
I want to provide feedback from an internal discussion with @tg9541 and @fajansen on this proposal:

We appreciate the use-case and proposal, but have two main change requests:

- we think that the name is misleading and could be misunderstood: For an "Automotive CAN Layered standard" many people would expect something different. The current approach is about "Automotive CAN to signals", and this should be reflected in the title and description. Otherwise some people would expect a "low cut", message based or binary realization of an "Automotive CAN" layered standard from the name. There could be another "Low Cut" Layered standard, and we should keep this possibility open by a suitable name of this one.
- Could the current approach be extended more generally from CAN to Automotive networks, i.e. "Automotive networks to signals"? This should be at least discussed. 

See also my comments on https://github.com/modelica/fmi-standard/issues/713

@andreas-junghanns  and other interested : we could also organize a discussion with my colleagues to further discuss this

2020-09-03 16:55 UTC, andreas-junghanns commented
>     * we think that the name is misleading and could be misunderstood: For an "Automotive CAN Layered standard" many people would expect something different. The current approach is about "Automotive CAN to signals", and this should be reflected in the title and description. Otherwise some people would expect a "low cut", message based or binary realization of an "Automotive CAN" layered standard from the name. There could be another "Low Cut" Layered standard, and we should keep this possibility open by a suitable name of this one.

I see your point, but no suggestion from you for a better name.
Please suggest better names, I am willing to consider, of course.
 
>     * Could the current approach be extended more generally from CAN to Automotive networks, i.e. "Automotive networks to signals"? This should be at least discussed.

Classic CAN shines with simplicity and this proposal was meant to be a useful and usable test in how to write a layered standard on top of FMI.
Extending to other network protocols will invite a number of difficult design decisions that I currently have no time to solve, given that the base standard text requires significant efforts to reach beta quality.
I will say more to the comments in #713.

> @andreas-junghanns and other interested : we could also organize a discussion with my colleagues to further discuss this

I will be available for such a meeting if an agenda and clear goals are presented.
A general session about what could possibly be done is currently not very helpful to move things forward - we are too busy with other parts of the standard (and my own wish list is a mile long already).

2020-09-03 18:03 UTC, chrbertsch commented
> I see your point, but no suggestion from you for a better name.
> Please suggest better names, I am willing to consider, of course.

Here are some proposals for names of this layered standard: 
* "CAN2Signals"
*  "Automotive CAN to signals mapping"
* "Automotive CAN (high cut)"
* "CAN Messages to Signals Mapping"

2020-09-03 20:50 UTC, andreas-junghanns commented
>     * "CAN2Signals"
>     * "Automotive CAN to signals mapping"
>     * "Automotive CAN (high cut)"
>     * "CAN Messages to Signals Mapping"

This is easy for me: CAN2Signals - thank you for the suggestion!
Short, precise, no special characters or spaces to confuse.
I will pretend this was the result of a vote and pick this for a title for now.

2020-09-16 17:30 UTC, closed without merging