#1180 : rename fmi3NewDiscreteStates to fmi3UpdateDiscreteStates
modelica/fmi-standard pull request #1224
Opened 2020-10-16 16:49 UTC by masoud-najafi

Following the decision on renaming fmi3NewDiscreteStates  to fmi3UpdateDiscreteStates (https://github.com/modelica/fmi-standard/issues/1180) , I renamed all occurrences of fmi3NewDiscreteStates.
We need also update the APIs in reference FMUs.
CC: @t-sommer

2020-10-16 18:01 UTC, chrbertsch approved these changes

2020-10-20 08:51 UTC, andreas-junghanns requested changes
`newDiscreteStatesNeeded` is still around - should we not also change that argument accordingly?

2020-10-20 08:54 UTC, masoud-najafi commented
> 
> 
> `newDiscreteStatesNeeded` is still around - should we not also change that argument accordingly?

If "updateDiscreteStatesNeeded" is fine, I will replace them all.

2020-10-20 09:02 UTC, chrbertsch commented
Perhaps  add "of": updateOfDiscreteStatesNeeded"?

2020-10-20 14:33 UTC, andreas-junghanns commented
> 
> 
> Perhaps add "of": updateOfDiscreteStatesNeeded"?

I think without "of" is better, because updateDiscreteStates is the function call, updateDiscreteStatesNeeded requires another call to that function. And it would be shorter too.

2020-10-20 16:51 UTC, t-sommer requested changes

2020-10-20 16:51 UTC, t-sommer commented on headers/fmi3FunctionTypes.h
> +typedef fmi3Status fmi3UpdateDiscreteStatesTYPE(fmi3Instance instance,
Shouldn't this be `discreteStatesNeedUpdate` instead of `updateDiscreteStatesNeeded`?

2020-10-20 20:34 UTC, t-sommer approved these changes

2020-10-20 20:49 UTC, chrbertsch approved these changes

2020-10-21 07:45 UTC, andreas-junghanns approved these changes

2020-10-21 07:46 UTC, merged