Use C99 int/bool types for all types
modelica/fmi-standard pull request #1311
Opened 2021-02-19 15:11 UTC by pmai

Given that we already depend on the C99 integer types for our integer
types, we might as well switch to use the C99 _Bool type and integer
types for all other typedefs to make the interface ABI more stable.

This reflects the discussions in the design meeting on 2021-02-19

Checklist

* [ ] Used a [personal fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) of the repository to propose changes.
* [ ] [Built the specification](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#building-the-specification-document).
* [ ] [Re-generated schema figures](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#changing-the-xsd-schemas).
* [ ] [Linted the documents](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#building-the-specification-document).

See also PR #1102 which started the discussion.

2021-02-19 15:51 UTC, andreas-junghanns requested changes
I think fmi3Clock should be uint8_t as well, because we define two macros with values to use (as opposed to using true and false).

2021-02-19 23:11 UTC, t-sommer commented
> I think fmi3Clock should be uint8_t as well, because we define two macros with values to use (as opposed to using true and false).

Did you mean `uint32_t`?

2021-02-20 18:35 UTC, andreas-junghanns commented
> > I think fmi3Clock should be uint8_t as well, because we define two macros with values to use (as opposed to using true and false).
> 
> Did you mean `uint32_t`?

I am old, I usually try to save bytes, but maybe uint32_t is the faster choice in todays platforms (seeing also that _Bool is now 32 bit). So, uint32_t would be ok with me.

2021-02-22 12:52 UTC, t-sommer approved these changes

2021-02-22 12:55 UTC, merged

2021-02-22 16:54 UTC, andreas-junghanns commented
This PR was merged with fmi3Clock still being of type _Bool.
What about fmi3ClockActive and fmi3ClockInactive macros?
These should not be assigned as values of a now _Bool clock.

@t-sommer: Can you at least comment here why I should not care about this inconsistency?

2021-02-22 17:45 UTC, pmai commented
> This PR was merged with fmi3Clock still being of type _Bool.
> What about fmi3ClockActive and fmi3ClockInactive macros?
> These should not be assigned as values of a now _Bool clock.

Why? _Bool is expected to take 0 and 1 as literal values, it only differs from int in that it will normalize all non-0 values to 1 on assignment.

We could include stdbool.h and use true and false but those are just macros and would needlessly pollute the namespace...