Clean up Clocks API and schema
modelica/fmi-standard pull request #1361
Opened 2021-03-19 23:04 UTC by t-sommer

TODOs:

- [ ] change "Clock with causality == input" to "input Clock"?
- [ ] remove excessive references to Clock within same chapter?

2021-03-21 12:35 UTC, andreas-junghanns commented
Observations:
 - you introduced argument descriptions with a new format "nValues::" - before I tried to be consistent with the "* nValues:" format. We should be consistent throughout the document.
 - achors like [[qualifier,`qualifier`]] seem a bit off (too low in that case).
 - I tried to not repeat descriptions of argument used over and over again, like `valueReferences`. In your case, if those valueReferences must point to specific types of variables, stating that is probably a good idea. But we should check the rest of the document for consistency in that respect.
 - sometimes you merge argument descriptions (e.g. `intervalCounters` and `resolutions`), sometimes you have them separate (e.g. `intervals` and `qualifiers`). I did not detect a pattern...
 - search for <<input>> <<clock>> to turn to <<inputClock>>
 - in the clocks-type table, we format `aperiodic` and `periodic` - but these are not keywords, right? Drop the ``?

Let me know and for most of these, I can add the changes to this PR.

2021-03-21 12:36 UTC, andreas-junghanns requested changes
See my previous comment...

2021-03-21 16:24 UTC, andreas-junghanns approved these changes

2021-03-22 13:41 UTC, TorstenBlochwitz approved these changes
Great work! Makes Clocks more to variables than before!

2021-03-22 13:41 UTC, merged