Relax requirement for including dependencies
modelica/fmi-standard pull request #1478
Opened 2021-07-08 11:49 UTC by t-sommer

fixes #1477

2021-07-08 15:10 UTC, andreas-junghanns requested changes
This is dangerous. Esssentially, this is opening a legal door to DLL hell.
I know we already have FMUs out there that are not fully static and are illegal that way but this way the importers are not to blame if things break.
Again: If we allow dynamic linking it will be unclear who is responsible about providing those dependencies.
Note: even for the simple case of VS, linking with /MD you are NOT allowed to ship the VS runtime stuff - the importer has to make sure the redistribution packages are installed. For each version of VS.
I am not saying that this is sometimes unavoidable, I know static linking is a luxury that sometimes is unatainable, but at least the standard should set clear expectations.
This has been discussed way to often this was repeatedly refused and I still think for good reasons.

This proposal here is way too soft. If we open the door for dymamic linking, we should at least:
 - require some form of dependency documentation
 - shift the burdon to the exporter if things fail, that is, proper error messages MUST be logged to the importer as ERROR to make sure the user knows the FMU makes a certain dynamic load request that the importer or the system it runs on must be fulfilled.

Needless to say: I would rather not allow this.

2021-07-09 08:44 UTC, t-sommer commented
> [...] error messages MUST be logged to the importer as ERROR to make sure the user knows the FMU makes a certain dynamic load request that the importer or the system it runs on must be fulfilled.

This is already required by the specification (see https://fmi-standard.org/docs/3.0-dev/#FMUStateSetable):

>  If a NULL pointer is returned, then instantiation failed. In that case, logMessage is called with detailed information about the reason.

> require some form of dependency documentation

The dependencies are already implicitly declared either in the shared library itself (for load time dependencies) or through the mandatory error message (for lazy loading).

@andreas-junghanns, can you propose a change that makes this clarifies this?

2021-07-13 11:24 UTC, chrbertsch commented
Isn't this related to the needsExecutionTool flag? 
If there is an external dependency for the FMU to be executed, IMHO this flag should be set and it should be documented, of what this dependency existst (and how to install tools, needed DLLs etc.)
see https://github.com/modelica/fmi-standard/issues/1470

2021-07-13 11:33 UTC, t-sommer commented
I think historically `needsExecutionTool` indicates the requirement to install an external tool in the sense of tool coupling. If we repurpose the flag to indicate _any_ dependency on external resources, we should probably rename it to `needsExternalResources` and update the documentation accordingly.

2021-07-15 22:36 UTC, casella commented
I understand a fundamental requirement of FMUs is to be self-contained and portable to the maximum possible extent, so that they can be reused and shipped to third parties with ease. So, the ideal situation is a self-contained set of C sources, that can be compiled with any standard ANSI C compiler, and/or a statically compiled DLL, that can run anywhere.

I fully agree with @andreas-junghanns' comment, in particular with this statement:
> If we allow dynamic linking it will be unclear **who is responsible about providing those dependencies**.". 

This is the killer argument for me.

I find @t-sommer's argument
>This proposal is by no means an invitation to link dynamically, but to legalize the large number of FMUs that are doing it already (for various reasons) and will continue to do it. Not allowing it (even though it is clearly discouraged) will e.g. lead to the exclusion of a large number of FMUs from the Cross-Check, because they are clearly illegal according to the current specification

rather questionable. 

We've already been in a similar situation 10 years ago, when it became clear that the Modelica Standard Library 3.2 was not standard at all, because in a quite large number of occasions it did not actually follow the Modelica Specification 3.2. That was obviously a big deal. The way we solved it was to fix the Modelica Standard Library as much as we could so that it actually followed the Specification, even though that actually required some work. I think we should do the same with those FMUs in the cross-check, i.e. re-generate them so that they actually follow the standard. Old FMUs that worked can still be used, but new ones should stick to the standard.

As it turned out back then, there were some features in the MSL that were actually quite cleverly designed and useful, e.g. the gravitity function in the outer System object of the MultiBody library, that was actually not allowed by the lookup rules of Modelica 3.2. In those cases, the best solution was to amend the Specification to allow them, which was actually done twice with 3.2r1 and 3.2r2. 

All this was done cooperatively with contribution from all tool vendors and library developers, and I believe that was a success story for the MA. I am convinced we should address this issue in the same spirit.

Summing up

- I agree with @andreas-junghanns that a world of self-contained FMUs that do not depend on DLLs is a better world
- I think the FMI Specification has a point in this respect and should not be relaxed light-heartedly
- MA standards should not legalize de-facto situations, but rather strive for good, rational, open, portable, reusable, and user-friendly software
- If it turns out that there is a real, _documented_ need of dependencies _in real applications_ (never mind the cross-check examples), the standard should explain clearly how they should be managed. I understand managing DLL hell is a hell of job, so I would personally avoid going in this direction
- Even if we allowed dependencies on DLLs, we should not put FMUs that actually have those dependencies in the FMI-cross-check pool of examples, because that would cause unnecessary waste of time and frustration. Most importantly, they will lead to unfair results, based on factors that are completely independent form the quality of implementation of FMUs, which is what the cross-check should certify

2021-07-18 17:30 UTC, t-sommer commented
> * If it turns out that there is a real, _documented_ need of dependencies _in real applications_ (never mind the cross-check examples), the standard should explain clearly how they should be managed. I understand managing DLL hell is a hell of job, so I would personally avoid going in this direction

You could argue that approach 1. (see above) is too hard to implement, but what speaks against approach 2. in your opinion?
I can give you a list of real world industrial applications where this is necessary for legal and efficiency reasons.

> * Even if we allowed dependencies on DLLs, we should not put FMUs that actually have those dependencies in the FMI-cross-check pool of examples, because that would cause unnecessary waste of time and frustration. Most importantly, they will lead to unfair results, based on factors that are completely independent form the quality of implementation of FMUs, which is what the cross-check should certify

The XC rules are not subject of this PR.

2021-07-19 07:49 UTC, andreas-junghanns approved these changes
I have no better suggestions and it seems clear that we need to relax our rules.
So with trepidation, I propose to merge this.
However, this needs further discussion in a whider group!

2021-07-21 09:39 UTC, chrbertsch requested changes
As discussed a flag `hasExternalDependencies` should be added similarly to "needsExecutionTool"

2021-07-21 09:52 UTC, t-sommer commented
> As discussed a flag `hasExternalDependencies` should be added similarly to "needsExecutionTool"

I'm aware of the discussion yesterday, however I think it introduces a redundancy, since this information is already contained in the presence (or absence) of the file.

2021-07-21 10:07 UTC, andreas-junghanns commented
> > As discussed a flag `hasExternalDependencies` should be added similarly to "needsExecutionTool"
> 
> I'm aware of the discussion yesterday, however I think it introduces a redundancy, since this information is already contained in the presence (or absence) of the file.

@chrbertsch : I was similarly cautious to accept this reduction, but @t-sommer pointed out that platform support must also be taken from the existence of files. So the mechanism to use a file as a "flag" is not a new mechanism.

2021-07-21 10:10 UTC, andreas-junghanns requested changes
Should we not point to the externalDependencies.* file in the text?

2021-07-21 11:47 UTC, hubertus65 reviewed
I agree with this proposal.

2021-07-21 11:53 UTC, chrbertsch commented
> 
> 
> Should we not point to the externalDependencies.* file in the text?

I agree. I would suggest something like:  "If the FMU has external dependencies that are needed to load or simulate the FMU (examples: ...), a file hasExternalDependencies* must be present within the documentation folder, which contains a human-readanble list and/or description of these dependencies."

2021-07-21 11:56 UTC, chrbertsch approved these changes

2021-07-21 14:33 UTC, andreas-junghanns approved these changes

2021-07-21 14:59 UTC, merged