State that the value of the independent variable is not defined for SE
modelica/fmi-standard pull request #1479
Opened 2021-07-08 14:00 UTC by t-sommer

fixes #1458

2021-07-08 15:58 UTC, andreas-junghanns requested changes
In "5.2.2. State: Clock Activation Mode" t is used.
I don't think that the independent variable is "not defined" - it might be that some FMUs cannot return it, but when you call getXXX(), the variable you receive has a value w.r.t. the current time.
This currently proposed change confuses me more than it helps.
We must have approval from @IZacharias and @MBlesken.

2021-07-10 08:49 UTC, andreas-junghanns approved these changes

2021-07-21 13:28 UTC, t-sommer commented
FMI Design Meeting: The intermediate solution for zero-time execution model is to return the last activation time.

2021-07-26 09:55 UTC, MBlesken commented
@andreas-junghanns @t-sommer a getXXX() call by the simulation algorithm does not make sense (in SE) since it is the simulation algorithm itself that defines the time. This in mind I suggest to re-think
> FMI Design Meeting: The intermediate solution for zero-time execution model is to return the last activation time.

and consider retuning fmi3Error.

2021-07-26 11:42 UTC, MBlesken requested changes

2021-07-26 11:42 UTC, MBlesken commented on docs/2_4_common_schema.adoc
> +_[The main purpose of this variable is to define a quantity and unit for the independent variable.]_
quantitiy -> value?

2021-07-26 11:42 UTC, MBlesken commented on docs/2_4_common_schema.adoc
> +For <<fmi-for-scheduled-execution,Scheduled Execution>> the value of the independent variable is not defined _[since each <<model-partition>> has its own time]_.
the value is defined by the simulation algorithm

2021-08-03 14:51 UTC, pmai commented
If the current proposal would be that SE FMUs must have an independent variable, but that access to it would produce fmi3Error, then this must surely be reconsidered; why have a mandatory variable that is not allowed to be accessed (and causes simulation abort). Given that SE probably does not make sense for time units that are not s (or smaller factors thereof), this should be taken into account.

2021-08-04 14:03 UTC, merged