Some changes regarding intervalQualifier and getInterval
modelica/fmi-standard pull request #1592
Opened 2021-12-03 11:16 UTC by PTaeuberDS

This pull request includes following changes:

1. Some clarifications on the handling of intervalUnchanged and intervalNotYetKnown
2. Some restructuring of the SE code example
3. Adding getInterval to allowed functions of Clock Activation Mode
4. Removing of redundant parameters of clock specific getter and setter functions that are relicts of when clocks were not restricted to be scalars (e.g. nIntervals in getInterval). 
I'm not sure if the redundant parameter maybe was kept intentionally for some reasons. However, it is probably confusing for the reader to have two parameters for the same value. An alternative would be to state explicitly that nValueReferences and nIntervals always have the same value. Not very nice, though.

2021-12-06 08:07 UTC, andreas-junghanns approved these changes
Except for the example where I did not fully understand all changes, the rest are good.

2021-12-08 07:52 UTC, andreas-junghanns commented
@PTaeuberDS  : Do you keep this "in Draft" for a reason? We should discuss this later today in the design meeting, right?

2021-12-08 12:39 UTC, MBlesken requested changes
To me it seems you're attempting to make sense into a three value enum for the qualifier while I think that only two values are needed. As a consequence new requirements are imposed on the FMU exporter (generating the inst->CountdownClockQualifier = fmi3IntervalNotYetKnown). FYI @andreas-junghanns 

Request to change in the "Preemption section".

2021-12-08 17:06 UTC, PTaeuberDS commented
I moved the sentence to the place in the document where the qualifier is explained.
@MBlesken @andreas-junghanns Please have a look

2021-12-09 07:08 UTC, MBlesken requested changes
Please check if the SE Example has to updated for GetInterval now: "inst->CountdownClockQualifier = fmi3IntervalUnchanged;" must only be called if the qualifier was fmi3IntervalChanged, right? Then: OK

2021-12-09 09:14 UTC, PTaeuberDS commented
> Please check if the SE Example has to updated for GetInterval now: "inst->CountdownClockQualifier = fmi3IntervalUnchanged;" must only be called if the qualifier was fmi3IntervalChanged, right? Then: OK

Good catch. Done

2021-12-09 10:57 UTC, MBlesken approved these changes

2021-12-09 14:52 UTC, andreas-junghanns approved these changes
I reworked the qualifier value descriptions (again) - if you agree with the new wording, please merge. Otherwise let´s find some time to discuss and change this online.

2021-12-09 14:53 UTC, andreas-junghanns commented
@MBlesken : Warning: I meddled with the text again - you might want to read the section describing the interval qualifiers again.
@PTaeuberDS : I checked your code in snippets.c and agree with the logic.

2021-12-09 14:57 UTC, andreas-junghanns commented
> I moved the sentence to the place in the document where the qualifier is explained. @MBlesken @andreas-junghanns Please have a look

I did not agree (hence the rewite): The sentence did not explain "who" needs to keep book this way. And in essence, we should not - in the standard text that is - describe how implementation is done - we need to stay on the API side.
But I agreed that the mechanism wasn´t too clear and hope this is a bit clearer now... waiting for your judgement...

2021-12-13 08:24 UTC, TorstenBlochwitz approved these changes
OK, looks good.

2021-12-13 08:24 UTC, merged