Add mightReturnEarlyFromDoStep flag
modelica/fmi-standard pull request #1593
Opened 2021-12-03 15:32 UTC by andreas-junghanns

2021-12-03 17:42 UTC, masoud-najafi approved these changes

2021-12-03 17:57 UTC, chrbertsch requested changes
Change the argument of fmi3DoStep in the header file to eventHandlingIsRequired

2021-12-03 21:59 UTC, andreas-junghanns commented
> Change the argument of fmi3DoStep in the header file to eventHandlingIsRequired

Done.

2021-12-05 16:09 UTC, chrbertsch approved these changes

2021-12-06 08:02 UTC, merged