Add full description for CS version of fmi3EnterEventMode
modelica/fmi-standard pull request #1736
Opened 2022-04-05 10:44 UTC by pmai

This should clarify and correct the presentation of fmi3EnterEventMode for CS.

It narrows down the allowable values for unused arguments, and corrects errors in both descriptions with regards to CS use.

2022-04-05 19:36 UTC, chrbertsch requested changes

2022-04-05 19:36 UTC, chrbertsch commented on docs/3_2_model_exchange_api.adoc
> +* `stateEvent` signals a <<state-event>>, `stateEvent` is triggered by a domain change of an event indicator.
"domain change" of an event indicator (used in several places)  is not clearly defined and does not seem to be broadly used in literature. 
If we stick with this, we must define it.
Do you mean a change of sign?

2022-04-06 08:42 UTC, andreas-junghanns approved these changes

2022-04-06 09:17 UTC, chrbertsch approved these changes

2022-04-06 11:04 UTC, KarlWernersson approved these changes

2022-04-06 14:00 UTC, merged