Fix typo in 2.3.1: Setable -> Settable
modelica/fmi-standard pull request #1740
Opened 2022-04-08 09:03 UTC by GallLeo

"Setable" does not seem to be an English word? Can we use "Settable" instead?

Note: images and links have to be fixed, as well.

Checklist

* [x] Used a [personal fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) of the repository to propose changes.
* [ ] [Built the specification](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#building-the-specification-document).
* [ ] [Re-generated schema figures](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#changing-the-xsd-schemas).
* [ ] [Linted the documents](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#building-the-specification-document).

Add your [meaningful description](https://github.com/modelica/fmi-standard/blob/master/CONTRIBUTING.adoc#bug-reports) here and reference any related issues with `#<issue>`.

2022-04-08 09:05 UTC, t-sommer approved these changes

2022-04-08 11:05 UTC, andreas-junghanns requested changes
The state machine images need this fix as well...

2022-04-08 18:50 UTC, andreas-junghanns commented
@t-sommer : Please check again - I did add changes to xrefs that failed to be resolved and fixed the state machine images

2022-04-08 19:44 UTC, andreas-junghanns approved these changes

2022-04-15 08:17 UTC, pmai approved these changes
Probably settable is also not really QE, but given the precedent of resettable fuses having entered the language I would think this is the preferred spelling.

2022-04-15 08:17 UTC, merged