Fix description of forbidden special values for real values in FMI 2.0.x
modelica/fmi-standard pull request #1785
Opened 2022-06-28 11:48 UTC by t-sommer

back-ports #1122 to FMI 2.0
fixes #1784

2022-06-28 12:23 UTC, chrbertsch requested changes
I think as we forbid "INF", "-INF" "NAN" in FMI 2.0.3, we should not allow these values in FMI 2.0.4., as we otherwise confuse users whether an FMU e.g. with an "INF" parameter in the XML is a "legal" FMU or not (it would be a valid FMI 2.0.4 FMU but an invalid FMI 2.0.3 FMU). There are importing tools out in the wild, that to not treat "INF" correctly.

My point in #1784 was only to rename "+INF" to "INF" in FMI 2.0.4, as this is how it is called in XML (and which confused users)

(I now also understand why this restriction was removed 3.0 following the discussion in #644 )

2022-06-28 12:25 UTC, andreas-junghanns approved these changes

2022-06-29 08:31 UTC, andreas-junghanns commented
> > There are importing tools out in the wild, that to not treat "INF" correctly.
> 
> If a tool cannot handle NANs (or any other value for that matter), it must raise an error. Allowing NANs in the XML will not change anything for the tool or the user (except that they cannot blame it on the FMU anymore).

A tool must be able to assume that an FMU follows the standard. FMI 2.0 is clear on not allowing these and the reasons where clear: too many different ways of actually writing the special numbers in the different standard libs writing floats and parsing them back. The "blame" is an important issue here: All tools have to follow the standard, also exporters!

2022-06-29 11:18 UTC, andreas-junghanns commented
> Using non-finite numbers in the API was always legal and must be handled by the FMU.

FMI 2.0.3 restricts that, if I may remind you by stating: "The special values NAN, +INF, -INF for variables values are not allowed in the FMI xml files." With that, an importer's behavior is undefined if it finds such values.

2022-06-29 11:22 UTC, pmai commented on docs/2_2_common_schema.adoc
```suggestion

The special values NAN, INF, +INF, and -INF for variables values are not allowed in the FMI XML files.

```

2022-06-29 11:25 UTC, pmai commented
> > Using non-finite numbers in the API was always legal and must be handled by the FMU.
> 
> FMI 2.0.3 restricts that, if I may remind you by stating: "The special values NAN, +INF, -INF for variables values are not allowed in the FMI xml files." With that, an importer's behavior is undefined if it finds such values.

But as @t-sommer rightly points out, that only applies to the XML, not to the API.

I've provided my suggestion of how the wording should change in 2.0.x, to clarify that obviously INF without the redundant + also falls under the prohibition (this always was the intent, and since the language talks about values and not lexical items, +INF and INF are the same value anyways, so this technically also does not expand the prohibition).

It is right and proper that 3.0 drops this whole nonsense sharade, but for 2.0.x we cannot retroactively drop it.

2022-06-29 11:29 UTC, chrbertsch approved these changes

2022-06-29 11:40 UTC, merged