Improved content description of binaries and resources dirs (#1822)
modelica/fmi-standard pull request #1832
Opened 2022-11-18 14:12 UTC by friedrichatgc

Clearly define which files should go the binaries and resources dir of the FMU which when these dirs must be unpacked by the FMU importer.

2022-11-18 16:41 UTC, andreas-junghanns approved these changes

2022-11-18 18:20 UTC, t-sommer requested changes

2022-11-18 18:20 UTC, t-sommer commented on docs/2_5_fmu_distribution.adoc
> +A binary FMU must contain, for each supported platform, the shared library `<modelIdentifier>.{dll|dylib|so}` and all files which are needed to load this shared library
An FMU may  also ship with static libraries.

2022-11-23 13:23 UTC, chrbertsch commented
Webmeeting: @t-sommer : I will come up with proposals to simplify the wording. Could also be backported to FMI 2.0.x

2022-11-23 21:06 UTC, pmai reviewed
Content-wise seems the right thing to me, tightened wording would be OK by me.

2022-11-23 21:06 UTC, pmai commented on docs/2_5_fmu_distribution.adoc
> +Hence, the FMU importer is not needed to unpack these files during execution of the FMU.
```suggestion
Hence, the FMU importer is not required to unpack these files during execution of the FMU.
```

2022-12-18 14:20 UTC, t-sommer requested changes

2022-12-18 14:20 UTC, t-sommer commented on docs/2_5_fmu_distribution.adoc
> +This is needed since the shared library may search for other files, needed during library load time, relative to its own file location.
This reasoning should not be normative.

2022-12-18 14:20 UTC, t-sommer commented on docs/2_5_fmu_distribution.adoc
> +A static library binary FMU must contain, for each supported platform and ABI, the static library `<modelIdentifier>.{a|lib}` and all files which are needed to link with this static library
Requiring "all files which are needed to link with this static library" to be contained in the FMU would render any FMU illegal that has external dependencies (caused by the static library).

2022-12-18 14:20 UTC, t-sommer commented on docs/2_5_fmu_distribution.adoc
> +These binary files may go into an ABI specific subdirectory, see <<platform-tupe-definition>> also for linking instructions.
This folder must not be a subdirectory of the platform binary directory but the `binaries` directory. Also, we should not allow spreading libraries and dependencies across multiple folders.

2022-12-18 14:24 UTC, t-sommer commented on docs/2_5_fmu_distribution.adoc
> +These binary files may go into an ABI specific subdirectory, see <<platform-tupe-definition>> also for linking instructions.
IMHO, we should have a concise set of rules for the naming and availability at runtime in the spec and move all the reasoning and explanations to the implementers guide.

2022-12-19 08:19 UTC, andreas-junghanns commented
All: Markus dropped off our planet. Any change we want to be made, we must now make. @t-sommer : will you take over? You seem most interested...

2023-01-31 14:27 UTC, chrbertsch commented
FMI Design Meeting: 
Pierre: the original intent was to clarify that in binaries only things are put that are needed at link or load time.
For things needed at runtime, they have to be put in resources
Torsten: Give a rational that the FMU may depend on files that must be present during load time. 
Pierre: Link time is different for statically or dynamically linked library.
Pierre: There is a whole section in the IG! The reason for this PR was, that people were unclear that platform specific files can be in resources.
Pierre: Similar questions currently arise in the XCP LS, so a clarification is welcome. E.g. would not expect A2L files in resources or binaries, as they are not needed during runtime. Only for specific use cases the A2L file would be needed during runtime ...

Christian: I will create a new PR

2023-01-31 19:38 UTC, chrbertsch commented
Superseded by #1849

2023-01-31 19:47 UTC, closed without merging