Clarify earlyReturn from fmi3DoStep
modelica/fmi-standard pull request #1845
Opened 2022-12-14 20:40 UTC by Maplesoft-fmigroup

Added a comment that this should not be used if the step terminated early due to an error to resolve #1844

2022-12-15 07:09 UTC, andreas-junghanns approved these changes
@pmai : Intend and wording ok?

2022-12-15 11:14 UTC, pmai requested changes
I think the wording is fine for me, but given that fmi3Discard also still exists, we should point to that as well, as alternatives to earlyReturn being true.

2022-12-15 11:14 UTC, pmai commented on docs/4_2_co-simulation_api.adoc
> +Instead, the function must return with an error code (<<fmi3Error>> or <<fmi3Fatal>>).
I think we also must point to fmi3Discard, which is another way the function can return immediately (without earlyReturn being true), e.g.:

```suggestion
Instead, the function must return with an error code (<<fmi3Error>> or <<fmi3Fatal>>).
Alternatively, the function can return with <<fmi3Discard>>, if the FMU is in the same state as before the call, i.e. the output argument values are undefined, but the computation may continue.
```

2023-01-10 18:58 UTC, chrbertsch approved these changes

2023-01-10 21:51 UTC, andreas-junghanns approved these changes

2023-01-17 15:36 UTC, pmai approved these changes

2023-01-17 15:43 UTC, merged