clarify usage of structural parameters in glossary
modelica/fmi-standard pull request #1850
Opened 2023-01-31 19:48 UTC by chrbertsch

fixes #1821

2023-02-01 19:39 UTC, pmai requested changes
I think this should mention reconfiguration mode, and set of the example more clearly.

2023-02-01 19:39 UTC, pmai commented on docs/7___appendix.adoc
> +|A parameter that can be set in <<ConfigurationMode>> before <<InitializationMode>>, e.g.,  for influencing the size and/or dimensionality of an array variable of an FMU.
```suggestion
|A parameter that can be changed in <<ConfigurationMode>>, i.e. prior to <<InitializationMode>>, and, if tuneable, also in <<ReconfigurationMode>>.
Structural parameters can be used to influence the size and/or dimensionality of array variables of an FMU, for example.
```

2023-02-05 11:57 UTC, andreas-junghanns approved these changes
The end of the second sentence leaves the door open to other uses of structural parameters (as @TorstenBlochwitz keeps reminding us). Maybe, just maybe, this could be more explicit?

2023-02-12 16:59 UTC, pmai approved these changes

2023-02-14 14:07 UTC, merged