Describe that fmi2reset can be called in case of fmi2error
modelica/fmi-standard pull request #1974
Opened 2024-09-10 11:34 UTC by chrbertsch

resolves #1946

2024-10-08 13:21 UTC, Maplesoft-fmigroup commented on docs/2_1_common_api.adoc
>  There might be cases where the environment can fix such errors (eventually with the help oft the user),
oft -> of

2024-10-08 13:36 UTC, pmai requested changes
Looks good, just keeping the instance wording seems like a good idea to not suggest that the whole FMU is reset. Should also fix the oft autocorrect typo while we are at it.

2024-10-08 13:36 UTC, pmai commented on docs/2_1_common_api.adoc
> +It is also possible to reset the FMU by calling `fmi2Reset`.
```suggestion
It is also possible to reset the instance of the FMU by calling `fmi2Reset`.
```

2024-10-14 11:04 UTC, t-sommer commented
@pmai, can you please re-review?

2024-10-14 11:07 UTC, pmai approved these changes

2024-10-16 12:49 UTC, merged